name: Extension VSIX
on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check src/**
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: |
            args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm tsc -p tsconfig.test.json
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm unit-test
      - uses: GabrielBB/xvfb-action@v1.6
        with:
          run: pnpm integration-test
