name: Release Extension
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # needs: test
    steps:
      - run: npm -v
      - run: node -v
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: |
            args: [--frozen-lockfile, --strict-peer-dependencies]
      # its fine until we don't use version in bundle somewhere
      - run: pnpm build
      - run: pnpm unit-test
      - run: pnpm lint
      - uses: GabrielBB/xvfb-action@v1.6
        with:
          run: pnpm integration-test
      - run: pnpx zardoy-release vscode-extension
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
